apiVersion: v1
kind: Pod
metadata:
  name: registry-backup2
  namespace: ark
spec:
  initContainers:
  - name: init-docker
    image: docker:dind
    command:
    - sh
    - -c
    - |
      mkdir -p /etc/docker
      echo '{ "insecure-registries" : ["10.72.80.228:80"] }' > /etc/docker/daemon.json
    volumeMounts:
    - name: docker-config
      mountPath: /etc/docker
  containers:
  - name: backup
    image: docker:dind
    securityContext:
      privileged: true
    command: ["sh", "-c", "dockerd &>/dev/null & sleep infinity"]
    volumeMounts:
    - name: backup-data
      mountPath: /backup
    - name: docker-config
      mountPath: /etc/docker
  volumes:
  - name: backup-data
    emptyDir: {}
  - name: docker-config
    emptyDir: {}