version: '3.8'

services:
  unirig-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: unirig-service:latest
    container_name: unirig-container
    ports:
      - "4000:8000"
    volumes:
      # 모델 파일을 호스트에서 마운트 (unirig.pth 파일을 여기에 배치)
      - ./models:/app/models
      # 임시 파일 저장공간
      - ./temp:/app/temp
      # 로그 파일 저장공간  
      - ./logs:/app/logs
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
      - GPU_DEVICE_ID=0
      - GPU_NAME=NVIDIA_A10 # 테스트는 A10 만 사용
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']  # A10 GPU만 사용 (GPU 0번)
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx 리버스 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    container_name: unirig-nginx
    ports:
      - "4080:80"
      - "4443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL 인증서 (HTTPS 사용시)
    depends_on:
      - unirig-service
    restart: unless-stopped
    profiles:
      - production  # docker-compose --profile production up 으로 실행

networks:
  default:
    name: unirig-network