apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2024-09-28T11:28:20Z","generation":2,"name":"db","namespace":"sewio-uwb","resourceVersion":"1081641529","uid":"ee937a13-1462-4473-ae34-87c1b1573c58"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"db"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"db"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-role.kubernetes.io/kiss-ephemeral-control-plane","operator":"DoesNotExist"}]},"weight":1}],"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"node-role.kubernetes.io/kiss","operator":"In","values":["ControlPlane"]}]}]}}},"containers":[{"env":[{"name":"MYSQL_USER","value":"laravel_user"},{"name":"MYSQL_PASSWORD_FILE","value":"/run/secrets/db_password"},{"name":"MYSQL_ROOT_USERNAME","value":"sewiortls"},{"name":"MYSQL_ROOT_PASSWORD_FILE","value":"/run/secrets/db_root_password"},{"name":"INTERNAL_API_KEY_FILE","value":"/run/secrets/internal_api_key"}],"image":"quay.io/netaiy/sewio-uwb-sewiodb:3.1.0","imagePullPolicy":"IfNotPresent","name":"db","ports":[{"containerPort":3306,"name":"db","protocol":"TCP"}],"resources":{},"securityContext":{"capabilities":{"add":["CAP_SYS_NICE"]}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/docker-entrypoint-initdb.d","name":"db-dump"},{"mountPath":"/docker-entrypoint-initdb.d/migrate","name":"db-dump-migrate-writable","subPath":"src"},{"mountPath":"/var/lib/mysql","name":"persistent-mysql"},{"mountPath":"/run/secrets/db_password","name":"secret","subPath":"db_password.txt"},{"mountPath":"/run/secrets/db_root_password","name":"secret","subPath":"db_root_password.txt"},{"mountPath":"/run/secrets/internal_api_key","name":"secret","subPath":"internal_api_key.txt"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"ark-registry"}],"initContainers":[{"args":["/src","/dst"],"command":["cp","-r"],"image":"docker.io/library/busybox:latest","imagePullPolicy":"Always","name":"init-copy-writeable-files","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/src","name":"db-dump-migrate"},{"mountPath":"/dst","name":"db-dump-migrate-writable"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"db-dump"},"name":"db-dump"},{"configMap":{"defaultMode":420,"name":"db-dump-migrate"},"name":"db-dump-migrate"},{"emptyDir":{},"name":"db-dump-migrate-writable"},{"name":"persistent-mysql","persistentVolumeClaim":{"claimName":"mysql-storage"}},{"name":"secret","secret":{"defaultMode":420,"secretName":"uwb"}}]}}},"status":{"conditions":[{"lastTransitionTime":"2024-10-09T17:46:31Z","lastUpdateTime":"2024-10-09T17:46:54Z","message":"ReplicaSet \"db-6cb5f76d44\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-10-09T17:54:03Z","lastUpdateTime":"2024-10-09T17:54:03Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"}],"observedGeneration":2,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-10-09T18:23:50Z"
  generation: 1
  name: db
  namespace: sewio-uwb
  resourceVersion: "1081738568"
  uid: 3b63dc17-755b-45af-a53d-33193faaaf41
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: db
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/kiss-ephemeral-control-plane
                operator: DoesNotExist
            weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/kiss
                operator: In
                values:
                - ControlPlane
      containers:
      - env:
        - name: MYSQL_USER
          value: laravel_user
        - name: MYSQL_PASSWORD_FILE
          value: /run/secrets/db_password
        - name: MYSQL_ROOT_USERNAME
          value: sewiortls
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: /run/secrets/db_root_password
        - name: INTERNAL_API_KEY_FILE
          value: /run/secrets/internal_api_key
        image: quay.io/netaiy/sewio-uwb-sewiodb:3.1.0
        imagePullPolicy: IfNotPresent
        name: db
        ports:
        - containerPort: 3306
          name: db
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - CAP_SYS_NICE
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: db-dump
        - mountPath: /docker-entrypoint-initdb.d/migrate
          name: db-dump-migrate-writable
          subPath: src
        - mountPath: /var/lib/mysql
          name: persistent-mysql
        - mountPath: /run/secrets/db_password
          name: secret
          subPath: db_password.txt
        - mountPath: /run/secrets/db_root_password
          name: secret
          subPath: db_root_password.txt
        - mountPath: /run/secrets/internal_api_key
          name: secret
          subPath: internal_api_key.txt
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ark-registry
      initContainers:
      - args:
        - /src
        - /dst
        command:
        - cp
        - -r
        image: docker.io/library/busybox:latest
        imagePullPolicy: Always
        name: init-copy-writeable-files
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /src
          name: db-dump-migrate
        - mountPath: /dst
          name: db-dump-migrate-writable
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: db-dump
        name: db-dump
      - configMap:
          defaultMode: 420
          name: db-dump-migrate
        name: db-dump-migrate
      - emptyDir: {}
        name: db-dump-migrate-writable
      - name: persistent-mysql
        persistentVolumeClaim:
          claimName: mysql-storage
      - name: secret
        secret:
          defaultMode: 420
          secretName: uwb
status:
  conditions:
  - lastTransitionTime: "2024-10-09T18:23:50Z"
    lastUpdateTime: "2024-10-09T18:23:58Z"
    message: ReplicaSet "db-6cb5f76d44" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-10-09T18:27:01Z"
    lastUpdateTime: "2024-10-09T18:27:01Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
