apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"8"},"creationTimestamp":"2024-09-28T11:28:20Z","generation":10,"name":"rtlsio","namespace":"sewio-uwb","resourceVersion":"1114050865","uid":"1073acb0-f7a1-4748-907b-d2c0a3d005a3"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"rtlsio"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2024-10-17T16:44:39+09:00"},"creationTimestamp":null,"labels":{"name":"rtlsio"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-role.kubernetes.io/kiss-ephemeral-control-plane","operator":"DoesNotExist"}]},"weight":1}],"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"node-role.kubernetes.io/kiss","operator":"In","values":["ControlPlane"]},{"key":"node-role.kubernetes.io/sewio-uwb","operator":"Exists"}]}]}}},"containers":[{"env":[{"name":"JWT_SECRET_FILE","value":"/run/secrets/jwt_secret"},{"name":"INTERNAL_API_KEY_FILE","value":"/run/secrets/internal_api_key"},{"name":"WWW_HOST","value":"www"}],"image":"quay.io/netaiy/sewio-uwb-rtls-io:3.1.0","imagePullPolicy":"IfNotPresent","name":"rtlsio","ports":[{"containerPort":5959,"name":"http","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/home/rtlsio","name":"persistent-rtlsio"},{"mountPath":"/run/secrets/jwt_secret","name":"secret","subPath":"jwt_secret.txt"},{"mountPath":"/run/secrets/internal_api_key","name":"secret","subPath":"internal_api_key.txt"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"ark-registry"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"persistent-rtlsio","persistentVolumeClaim":{"claimName":"rtlsio"}},{"name":"secret","secret":{"defaultMode":420,"secretName":"uwb"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-10-09T17:52:29Z","lastUpdateTime":"2024-10-17T07:47:01Z","message":"ReplicaSet \"rtlsio-77f88c8d57\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-10-17T16:07:15Z","lastUpdateTime":"2024-10-17T16:07:15Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":10,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-09-28T11:28:20Z"
  generation: 11
  name: rtlsio
  namespace: sewio-uwb
  resourceVersion: "1134824870"
  uid: 1073acb0-f7a1-4748-907b-d2c0a3d005a3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: rtlsio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: vlan-210-mobilex-beacons-manager
        kubectl.kubernetes.io/restartedAt: "2024-10-17T16:44:39+09:00"
      creationTimestamp: null
      labels:
        name: rtlsio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/kiss-ephemeral-control-plane
                operator: DoesNotExist
            weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/kiss
                operator: In
                values:
                - ControlPlane
              - key: node-role.kubernetes.io/sewio-uwb
                operator: Exists
      containers:
      - env:
        - name: JWT_SECRET_FILE
          value: /run/secrets/jwt_secret
        - name: INTERNAL_API_KEY_FILE
          value: /run/secrets/internal_api_key
        - name: WWW_HOST
          value: www
        image: quay.io/netaiy/sewio-uwb-rtls-io:3.1.0
        imagePullPolicy: IfNotPresent
        name: rtlsio
        ports:
        - containerPort: 5959
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/rtlsio
          name: persistent-rtlsio
        - mountPath: /run/secrets/jwt_secret
          name: secret
          subPath: jwt_secret.txt
        - mountPath: /run/secrets/internal_api_key
          name: secret
          subPath: internal_api_key.txt
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ark-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: persistent-rtlsio
        persistentVolumeClaim:
          claimName: rtlsio
      - name: secret
        secret:
          defaultMode: 420
          secretName: uwb
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-10-09T17:52:29Z"
    lastUpdateTime: "2024-10-18T15:04:30Z"
    message: ReplicaSet "rtlsio-6cbb67bb6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-10-23T01:34:10Z"
    lastUpdateTime: "2024-10-23T01:34:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
