apiVersion: v1
kind: Pod
metadata:
  name: temp-permissions-pod
  namespace: sewio-uwb
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'chmod -R 777 /data && chown -R 999:999 /data && sleep 3600']
    volumeMounts:
    - name: mysql-storage
      mountPath: /data
  volumes:
  - name: mysql-storage
    persistentVolumeClaim:
      claimName: mysql-storage
  restartPolicy: Never