apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: name-twin
data:
  loki-config.yaml: |
    server:
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: inmemory

    ingester:
      lifecycler:
        address: $(POD_IP)
        ring:
          kvstore:
            store: inmemory
        final_sleep: 0s
      chunk_idle_period: 30m
      chunk_retain_period: 30s
      max_transfer_retries: 0

    limits_config:
      retention_period: 168h   

    schema_config:
      configs:
        - from: 2022-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    compactor:
      shared_store: filesystem
      working_directory: /data/loki/boltdb-shipper-compactor

    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h