apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: name-twin
  labels:
    ark.ulagbulag.io/test-ip-pool: "true"
spec:
  ports:
  - port: 3100
    name: http
  - port: 9095
    name: grpc
  selector:
    app: loki
  type: LoadBalancer