apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-metrics-collector-pvc
  namespace: name-twin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block