apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwb-collection-deployment
  namespace: name-twin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uwb-rlts
  template:
    metadata:
      labels:
        app: uwb-rlts
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - d0663000-9770-11e9-8000-3cecef55ef5c
                      - d15f2200-936a-11e9-8000-3cecef55f0e8
      containers:
      - name: uwb-rlts
        image: ttyy441/uwb-collection:1.1.3
        env: # 환경 변수 추가 섹션
        # PostgreSQL 환경 변수
        - name: DB_HOST
          value: "10.79.1.13"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "uwb"
        - name: DB_USER
          value: "myuser"
        - name: DB_PASSWORD # Secret 사용 권장
          value: "netAi007!"   
        - name: WEBSOCKET_URL # WebSocket URL을 위한 환경 변수
          value: "ws://10.65.153.171/sensmapserver/api"
        - name: SEWIO_API_KEY
          value: "17254faec6a60f58458308763"
        - name: SEWIO_RECONNECT_DELAY
          value: "5"
        - name: PYTHONUNBUFFERED 
          value: "1"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "10.79.1.1:9094" # 콤마로 구분
        - name: KAFKA_TOPIC
          value: "uwb_raw" # 실제 카프카 토픽 이름          
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/ceph-pvc
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: config-pvc