# Camera Agent Visibility Server 를 위한 Web-UI Deployment, SVC

apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-agent-visiblity-frontend
  namespace: name-twin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-agent-visiblity-frontend
  template:
    metadata:
      labels:
        app: camera-agent-visiblity-frontend
    spec:
      containers:
      - name: camera-agent-visiblity-frontend
        image: ttyy441/camera-agent-ui:0.2
        env:
        - name: API_BASE_URL
          value: "http://10.79.1.7:5111"  # agent-service svc 주소임 
        ports:
        - containerPort: 8112

---
apiVersion: v1
kind: Service
metadata:
  name: camera-agent-ui-service
  namespace: name-twin
  labels:
    ark.ulagbulag.io/is-dt-external: "true"
    ark.ulagbulag.io/test-ip-pool: "true"
spec:
  type: LoadBalancer
  selector:
    app: camera-agent-visiblity-frontend
  ports:
  - port: 3111
    targetPort: 8112