# YAML for SVC deploying Camera Agent to MobileX Station for testing purposes 

apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: vine-session-name-wow20
  labels:
    ark.ulagbulag.io/is-external: "true"
    ark.ulagbulag.io/is-private: "true"
spec:
  selector:
    app: agent  
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8000  
  type: ClusterIP