apiVersion: v1
kind: Service
metadata:
  name: nats-cluster
  namespace: nats-io
spec:
  clusterIP: None  # 헤드리스 서비스로 설정
  selector:
    nats_cluster: nats-cluster
  ports:
    - name: client
      port: 4222
      targetPort: 4222
      protocol: TCP
    - name: cluster
      port: 6222
      targetPort: 6222
      protocol: TCP
