apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: strimzi-kafka-operator
  labels:
    ark.ulagbulag.io/test-ip-pool: "true" 
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: kafdrop
