apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: strimzi-kafka-operator
spec:
  kafka:
    version: 3.5.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          # 각 브로커 서비스에 라벨 추가
          brokers:
            - broker: 0
              advertisedHost: 210.125.85.70
              advertisedPort: 9094
              labels:
                ark.ulagbulag.io/is-external: "true"
            - broker: 1
              advertisedHost: 210.125.85.71
              advertisedPort: 9094
              labels:
                ark.ulagbulag.io/is-external: "true"
            - broker: 2
              advertisedHost: 210.125.85.69
              advertisedPort: 9094            
              labels:
                ark.ulagbulag.io/is-external: "true"
          # 부트스트랩 서비스에 라벨 추가
          bootstrap:
            labels:
              ark.ulagbulag.io/is-external: "true"
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "3.5"
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: ceph-block
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - d0663000-9770-11e9-8000-3cecef55ef5c
                        - d15f2200-936a-11e9-8000-3cecef55f0e8
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: ceph-block
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - d0663000-9770-11e9-8000-3cecef55ef5c
                        - d15f2200-936a-11e9-8000-3cecef55f0e8
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 1Gi
          cpu: 1000m
        limits:
          memory: 2Gi
          cpu: 2000m
    userOperator:
      resources:
        requests:
          memory: 1Gi
          cpu: 1000m
        limits:
          memory: 2Gi
          cpu: 2000m