 # Kafka Cluster에서 새로운 Topic 생성하는 파일

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inyong-joystick
  namespace: name-twin
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    max.message.bytes: 20485760  # 약 20MB 메시지 크기
    retention.ms: 3600000      # 1주일(7일) 보관 1시간 (3,600,000ms) 보관