apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 20s
      scrapeTimeout: 15s
  namespaceSelector:
    matchNames:
      - strimzi-kafka-operator
  selector:
    matchLabels:
      app.kubernetes.io/component: kafka-metrics
      app.kubernetes.io/instance: strimzi-kafka-operator.kafka-metrics