 # Kafka Cluster 외부 접근용 IP 및 Port 개방
 # Example: kubectl get svc -n strimzi-kafka-operator

apiVersion: v1
kind: Service
metadata:
  name: kafka-external-service
  namespace: strimzi-kafka-operator
  labels:
    ark.ulagbulag.io/is-external: "true"  
spec:
  type: LoadBalancer
  ports:
    - name: main 
      port: 9094
      targetPort: 9094
      protocol: TCP
    - name: broker-0
      port: 9095
      targetPort: 9095
      protocol: TCP
    - name: broker-1
      port: 9096
      targetPort: 9096
      protocol: TCP
    - name: broker-2
      port: 9097
      targetPort: 9097
      protocol: TCP
  selector:
    strimzi.io/cluster: kafka-cluster
    strimzi.io/name: kafka-cluster-kafka