apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: strimzi-kafka-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - d0663000-9770-11e9-8000-3cecef55ef5c  # 첫 번째 노드
                      - d15f2200-936a-11e9-8000-3cecef55f0e8  # 두 번째 노드
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKER_CONNECT
              value: "kafka-cluster-kafka-bootstrap:9092"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "2"
