# Kafka Consumer.sh , Producer.sh 와 같은 Client 실행해볼 수 있는 테스트용 Pod 생성 파일

apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: strimzi-kafka-operator
spec:
  containers:
  - name: kafka-client
    image: strimzi/kafka:latest
    command: [ "sleep", "infinity" ]
