apiVersion: v1
kind: Service
metadata:
  name: resource-collector
  namespace: name-twin
  labels:
    ark.ulagbulag.io/is-external: "true"
    ark.ulagbulag.io/is-private: "true"
  annotations:
    lbipam.cilium.io/ips: "10.255.255.1"
spec:
  selector:
    app: resource-collector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer