apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-viewer
  namespace: name-twin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-viewer-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: ["kiss.ulagbulag.io"]
  resources: ["boxes", "netboxes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-viewer-binding
subjects:
- kind: ServiceAccount
  name: resource-viewer
  namespace: name-twin
roleRef:
  kind: ClusterRole
  name: resource-viewer-role
  apiGroup: rbac.authorization.k8s.io