# Template 처럼 MobileX-Cluster 에 Ceph-pvc 생성할때 사용하는 yaml 파일이다.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-pvc
  namespace: spark-operator
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem
  #volumeMode: Block   # ReadWriteMany 로 사용할꺼면  Block 모드만 지원함