# mobilex-twin 네임스페이스에 git-clone-pod를 생성하고, 공용 util 파일들 업데이트해주는 git-clone-container를 실행한다.

apiVersion: v1
kind: Pod
metadata:
  name: git-clone-pod
  namespace: mobilex-twin
spec:
  containers:
  - name: git-clone-container
    image: alpine/git  # git을 사용할 수 있는 도커 이미지
    command: ["git", "clone", "https://github.com/your-repository/util-files.git", "/mnt/data"]
    volumeMounts:
    - name: data-volume
      mountPath: "/mnt/data"
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: ceph-pvc
