apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: mobilex-twin
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
  selector:
    app: jenkins
