apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2024-11-04T14:12:27Z","generation":2,"name":"www","namespace":"sewio-uwb","resourceVersion":"1179220119","uid":"e0974122-95a4-4846-8651-3116c23936e0"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"www"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"k8s.v1.cni.cncf.io/networks":"vlan-210-mobilex-beacons-manager-host-device","kubectl.kubernetes.io/restartedAt":"2024-10-17T16:02:23+09:00"},"creationTimestamp":null,"labels":{"name":"www"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-role.kubernetes.io/kiss-ephemeral-control-plane","operator":"DoesNotExist"}]},"weight":1}],"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"node-role.kubernetes.io/kiss","operator":"In","values":["ControlPlane"]},{"key":"node-role.kubernetes.io/sewio-uwb","operator":"Exists"}]}]}}},"containers":[{"args":["sed -i 's/\\(\\/var\\/www\\/html\\/\\)temporary-uploads\\//\\1sensmapserver\\/svgs\\/uploads\\/temporary\\//g' /var/www/html/studio/app/Http/Controllers/FileController.php \u0026\u0026 chown -R www-data:www-data /var/www/html/sensmapserver/svgs/uploads \u0026\u0026 exec docker-php-entrypoint /usr/bin/supervisord\n"],"command":["bash","-c"],"env":[{"name":"LOG_CHANNEL","value":"stderr"},{"name":"DB_HOST","value":"db"},{"name":"DB_PORT","value":"3306"},{"name":"DB_DATABASE","value":"rtls_main"},{"name":"DB_USERNAME","value":"laravel_user"},{"name":"DB_PASSWORD_FILE","value":"/run/secrets/db_password"},{"name":"DB_HOST_SECOND","value":"db"},{"name":"DB_PORT_SECOND","value":"3306"},{"name":"DB_DATABASE_SECOND","value":"sensmapserver"},{"name":"DB_USERNAME_SECOND","value":"laravel_user"},{"name":"DB_PASSWORD_SECOND_FILE","value":"/run/secrets/db_password"},{"name":"REDIS_HOST","value":"redis"},{"name":"REDIS_PORT","value":"6380"},{"name":"PHPMYADMIN_HOST","value":"phpmyadmin"},{"name":"PUBLISH_BROKER","value":"Disabled"}],"image":"quay.io/netaiy/sewio-uwb-core:3.1.0","imagePullPolicy":"IfNotPresent","name":"www","ports":[{"containerPort":80,"name":"http","protocol":"TCP"},{"containerPort":443,"name":"https","protocol":"TCP"},{"containerPort":5000,"protocol":"TCP"},{"containerPort":5001,"protocol":"TCP"},{"containerPort":5000,"protocol":"UDP"},{"containerPort":5001,"protocol":"UDP"},{"containerPort":5100,"protocol":"UDP"},{"containerPort":5101,"protocol":"UDP"},{"containerPort":6789,"protocol":"TCP"},{"containerPort":8000,"name":"http-8000","protocol":"TCP"},{"containerPort":8080,"name":"http-8080","protocol":"TCP"}],"resources":{},"securityContext":{"capabilities":{"add":["NET_RAW"]},"runAsGroup":0,"runAsUser":0},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/home/rtlsserver/migrate/configs","name":"storage-rtlsserver-migrate-configs"},{"mountPath":"/home/rtlsserver/migrate/matrices/clock","name":"storage-rtlsserver-migrate-matrices-clock"},{"mountPath":"/home/rtlsserver/migrate/matrices/coefficient","name":"storage-rtlsserver-migrate-matrices-coefficient"},{"mountPath":"/home/rtlsserver/migrate/matrices/position","name":"storage-rtlsserver-migrate-matrices-position"},{"mountPath":"/var/www/html/sensmapserver/svgs/uploads/plans","name":"persistent-core-plans"},{"mountPath":"/var/www/html/sensmapserver/svgs/uploads/temporary","name":"persistent-core-temporary"},{"mountPath":"/home/rtlsserver/persistent","name":"persistent-core-rtlsserver"},{"mountPath":"/home/sewiortls","name":"persistent-core-sewiortls"},{"mountPath":"/home/rtlsio","name":"persistent-rtlsio"},{"mountPath":"/run/secrets/db_password","name":"secret","subPath":"db_password.txt"},{"mountPath":"/run/secrets/internal_api_key","name":"secret","subPath":"internal_api_key.txt"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"ark-registry"}],"initContainers":[{"args":["echo madvise \u003e/host/sys/kernel/mm/transparent_hugepage/enabled \u0026\u0026 echo 0 \u003e /host/proc/sys/vm/nr_hugepages\n"],"command":["sh","-c"],"image":"docker.io/library/busybox:latest","imagePullPolicy":"Always","name":"disable-thp","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/host/proc","name":"host-proc"},{"mountPath":"/host/sys","name":"host-sys"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"storage-rtlsserver-migrate-configs"},"name":"storage-rtlsserver-migrate-configs"},{"configMap":{"defaultMode":420,"name":"storage-rtlsserver-migrate-matrices-clock"},"name":"storage-rtlsserver-migrate-matrices-clock"},{"configMap":{"defaultMode":420,"name":"storage-rtlsserver-migrate-matrices-coefficient"},"name":"storage-rtlsserver-migrate-matrices-coefficient"},{"configMap":{"defaultMode":420,"name":"storage-rtlsserver-migrate-matrices-position"},"name":"storage-rtlsserver-migrate-matrices-position"},{"name":"persistent-core-plans","persistentVolumeClaim":{"claimName":"sewio-plans"}},{"name":"persistent-core-temporary","persistentVolumeClaim":{"claimName":"sewio-temporary"}},{"name":"persistent-core-rtlsserver","persistentVolumeClaim":{"claimName":"rtlsserver"}},{"name":"persistent-core-sewiortls","persistentVolumeClaim":{"claimName":"sewio-rtls"}},{"name":"persistent-rtlsio","persistentVolumeClaim":{"claimName":"rtlsio"}},{"hostPath":{"path":"/proc","type":""},"name":"host-proc"},{"hostPath":{"path":"/sys","type":""},"name":"host-sys"},{"name":"secret","secret":{"defaultMode":420,"secretName":"uwb"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-11-04T14:12:27Z","lastUpdateTime":"2024-11-04T14:12:27Z","message":"ReplicaSet \"www-c664bb8bb\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-11-04T14:12:50Z","lastUpdateTime":"2024-11-04T14:12:50Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":2,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-11-05T01:07:22Z"
  generation: 1
  name: www
  namespace: sewio-uwb
  resourceVersion: "1446188288"
  uid: 762c8747-989a-441f-8903-a90e8fa1ef5c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: www
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: vlan-210-mobilex-beacons-manager-host-device
        kubectl.kubernetes.io/restartedAt: "2024-10-17T16:02:23+09:00"
      creationTimestamp: null
      labels:
        name: www
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/kiss-ephemeral-control-plane
                operator: DoesNotExist
            weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/kiss
                operator: In
                values:
                - ControlPlane
              - key: node-role.kubernetes.io/sewio-uwb
                operator: Exists
      containers:
      - args:
        - |
          sed -i 's/\(\/var\/www\/html\/\)temporary-uploads\//\1sensmapserver\/svgs\/uploads\/temporary\//g' /var/www/html/studio/app/Http/Controllers/FileController.php && chown -R www-data:www-data /var/www/html/sensmapserver/svgs/uploads && exec docker-php-entrypoint /usr/bin/supervisord
        command:
        - bash
        - -c
        env:
        - name: LOG_CHANNEL
          value: stderr
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: rtls_main
        - name: DB_USERNAME
          value: laravel_user
        - name: DB_PASSWORD_FILE
          value: /run/secrets/db_password
        - name: DB_HOST_SECOND
          value: db
        - name: DB_PORT_SECOND
          value: "3306"
        - name: DB_DATABASE_SECOND
          value: sensmapserver
        - name: DB_USERNAME_SECOND
          value: laravel_user
        - name: DB_PASSWORD_SECOND_FILE
          value: /run/secrets/db_password
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6380"
        - name: PHPMYADMIN_HOST
          value: phpmyadmin
        - name: PUBLISH_BROKER
          value: Disabled
        image: quay.io/netaiy/sewio-uwb-core:3.1.0
        imagePullPolicy: IfNotPresent
        name: www
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 5000
          protocol: TCP
        - containerPort: 5001
          protocol: TCP
        - containerPort: 5000
          protocol: UDP
        - containerPort: 5001
          protocol: UDP
        - containerPort: 5100
          protocol: UDP
        - containerPort: 5101
          protocol: UDP
        - containerPort: 6789
          protocol: TCP
        - containerPort: 8000
          name: http-8000
          protocol: TCP
        - containerPort: 8080
          name: http-8080
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_RAW
            - NET_ADMIN
          runAsGroup: 0
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/rtlsserver/migrate/configs
          name: storage-rtlsserver-migrate-configs
        - mountPath: /home/rtlsserver/migrate/matrices/clock
          name: storage-rtlsserver-migrate-matrices-clock
        - mountPath: /home/rtlsserver/migrate/matrices/coefficient
          name: storage-rtlsserver-migrate-matrices-coefficient
        - mountPath: /home/rtlsserver/migrate/matrices/position
          name: storage-rtlsserver-migrate-matrices-position
        - mountPath: /var/www/html/sensmapserver/svgs/uploads/plans
          name: persistent-core-plans
        - mountPath: /var/www/html/sensmapserver/svgs/uploads/temporary
          name: persistent-core-temporary
        - mountPath: /home/rtlsserver/persistent
          name: persistent-core-rtlsserver
        - mountPath: /home/sewiortls
          name: persistent-core-sewiortls
        - mountPath: /home/rtlsio
          name: persistent-rtlsio
        - mountPath: /run/secrets/db_password
          name: secret
          subPath: db_password.txt
        - mountPath: /run/secrets/internal_api_key
          name: secret
          subPath: internal_api_key.txt
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ark-registry
      initContainers:
      - args:
        - |
          echo madvise >/host/sys/kernel/mm/transparent_hugepage/enabled && echo 0 > /host/proc/sys/vm/nr_hugepages
        command:
        - sh
        - -c
        image: docker.io/library/busybox:latest
        imagePullPolicy: Always
        name: disable-thp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/proc
          name: host-proc
        - mountPath: /host/sys
          name: host-sys
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: storage-rtlsserver-migrate-configs
        name: storage-rtlsserver-migrate-configs
      - configMap:
          defaultMode: 420
          name: storage-rtlsserver-migrate-matrices-clock
        name: storage-rtlsserver-migrate-matrices-clock
      - configMap:
          defaultMode: 420
          name: storage-rtlsserver-migrate-matrices-coefficient
        name: storage-rtlsserver-migrate-matrices-coefficient
      - configMap:
          defaultMode: 420
          name: storage-rtlsserver-migrate-matrices-position
        name: storage-rtlsserver-migrate-matrices-position
      - name: persistent-core-plans
        persistentVolumeClaim:
          claimName: sewio-plans
      - name: persistent-core-temporary
        persistentVolumeClaim:
          claimName: sewio-temporary
      - name: persistent-core-rtlsserver
        persistentVolumeClaim:
          claimName: rtlsserver
      - name: persistent-core-sewiortls
        persistentVolumeClaim:
          claimName: sewio-rtls
      - name: persistent-rtlsio
        persistentVolumeClaim:
          claimName: rtlsio
      - hostPath:
          path: /proc
          type: ""
        name: host-proc
      - hostPath:
          path: /sys
          type: ""
        name: host-sys
      - name: secret
        secret:
          defaultMode: 420
          secretName: uwb
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-11-05T01:07:22Z"
    lastUpdateTime: "2024-11-05T01:07:58Z"
    message: ReplicaSet "www-674d98967b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-02-09T09:39:45Z"
    lastUpdateTime: "2025-02-09T09:39:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
