apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppygraph-pvc
  namespace: name-twin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-block