apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-browser-pvc
  namespace: name-twin 
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: name-twin  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          mkdir -p /mnt/ceph-pvc/config
          if [ ! -f /mnt/ceph-pvc/config/filebrowser_config.json ]; then
            echo '{ "address": "0.0.0.0", "port": 80, "baseURL": "", "database": "/mnt/ceph-pvc/database.db", "root": "/mnt/ceph-pvc" }' > /mnt/ceph-pvc/config/filebrowser_config.json
          else
            if ! jq -e '.address' /mnt/ceph-pvc/config/filebrowser_config.json > /dev/null 2>&1; then
              jq '.address = "0.0.0.0"' /mnt/ceph-pvc/config/filebrowser_config.json > /tmp/config.json && mv /tmp/config.json /mnt/ceph-pvc/config/filebrowser_config.json
            fi
          fi
          if [ -f /mnt/ceph-pvc/database.db ]; then # 이 부분 활성화
            rm -f /mnt/ceph-pvc/database.db
          fi
          chown -R 1000:1000 /mnt/ceph-pvc
        volumeMounts:
        - mountPath: "/mnt/ceph-pvc"
          name: cephfs-storage
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser
        volumeMounts:
        - mountPath: "/mnt/ceph-pvc"
          name: cephfs-storage
        ports:
        - containerPort: 80
        args: ["-c", "/mnt/ceph-pvc/config/filebrowser_config.json"]
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"  
      volumes:
      - name: cephfs-storage
        persistentVolumeClaim:
          claimName: file-browser-pvc  


---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: name-twin  
  labels:
    ark.ulagbulag.io/is-dt-external: "true"
    ark.ulagbulag.io/test-ip-pool: "true"
spec:
  selector:
    app: filebrowser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer