apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command: 
        - /bin/sh
        - -c
        - |
          mkdir -p /mnt/ceph-pvc/config
          if [ ! -f /mnt/ceph-pvc/config/filebrowser_config.json ]; then
            echo '{ "port": 80, "baseURL": "", "database": "/mnt/ceph-pvc/database.db", "root": "/mnt/ceph-pvc" }' > /mnt/ceph-pvc/config/filebrowser_config.json
          fi
          if [ -f /mnt/ceph-pvc/database.db ]; then
            rm -f /mnt/ceph-pvc/database.db
          fi
          chown -R 1000:1000 /mnt/ceph-pvc
        volumeMounts:
        - mountPath: "/mnt/ceph-pvc"
          name: cephfs-storage
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser
        volumeMounts:
        - mountPath: "/mnt/ceph-pvc"
          name: cephfs-storage
        ports:
        - containerPort: 80
        args: ["-c", "/mnt/ceph-pvc/config/filebrowser_config.json"]
      volumes:
      - name: cephfs-storage
        persistentVolumeClaim:
          claimName: file-pvc