apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-02-20T16:12:02Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: v1beta2-1.6.2-3.5.0
    argocd.argoproj.io/instance: mobilex-spark-operator
    helm.sh/chart: spark-operator-1.4.6
  name: spark-operator
  namespace: spark-operator
  resourceVersion: "1679754843"
  uid: c760d827-e861-4e54-a692-fe9f4920f441
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: spark-operator
      app.kubernetes.io/name: spark-operator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: spark-operator
        app.kubernetes.io/name: spark-operator
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/kiss-ephemeral-control-plane
                operator: DoesNotExist
            weight: 1
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/kiss
                operator: In
                values:
                - Compute
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/kiss
                operator: In
                values:
                - ControlPlane
                - Compute
      containers:
      - args:
        - -v=2
        - -logtostderr
        - -namespace=
        - -enable-ui-service=false
        - -ingress-url-format=
        - -controller-threads=10
        - -resync-interval=30
        - -enable-batch-scheduler=true
        - -label-selector-filter=
        - -enable-metrics=true
        - -metrics-labels=app_type
        - -metrics-port=10254
        - -metrics-endpoint=/metrics
        - -metrics-prefix=
        - -enable-webhook=true
        - -webhook-secret-name=spark-operator-webhook-certs
        - -webhook-secret-namespace=spark-operator
        - -webhook-svc-name=spark-operator-webhook-svc
        - -webhook-svc-namespace=spark-operator
        - -webhook-config-name=spark-operator-webhook-config
        - -webhook-port=8080
        - -webhook-timeout=30
        - -webhook-namespace-selector=
        - -webhook-object-selector=
        - -enable-resource-quota-enforcement=true
        image: docker.io/kubeflow/spark-operator:v1beta2-1.6.2-3.5.0
        imagePullPolicy: IfNotPresent
        name: spark-operator
        ports:
        - containerPort: 10254
          name: metrics
          protocol: TCP
        - containerPort: 8080
          name: webhook
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: spark-operator
      serviceAccountName: spark-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-20T16:12:02Z"
    lastUpdateTime: "2025-02-20T16:12:20Z"
    message: ReplicaSet "spark-operator-6db89f947d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-11T05:00:50Z"
    lastUpdateTime: "2025-05-11T05:00:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
