apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dt-otel-collector-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 20s
    scrapeTimeout: 15s
    metricRelabelings:
    - action: labelmap
      regex: ^container_(.+)
    - action: labelmap
      regex: ^pod_(.+)
    - action: labelmap
      regex: ^node_(.+)
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
  namespaceSelector:
    matchNames:
    - opentelemetry-operator
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: opentelemetry-operator.dt-otel-collector-metrics