apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: name-twin
  labels:
    ark.ulagbulag.io/is-external: "true"
    ark.ulagbulag.io/is-private: "true"  
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres
  type: LoadBalancer